/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_sandbox_bruteforce_BruteForceService */

#ifndef _Included_org_opensearch_knn_sandbox_bruteforce_BruteForceService
#define _Included_org_opensearch_knn_sandbox_bruteforce_BruteForceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    initIndex
 * Signature: (JILjava/util/Map;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_initIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    insertToIndex
 * Signature: ([IJIJ)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_insertToIndex
  (JNIEnv *, jclass, jintArray, jlong, jint, jlong);

/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    writeIndex
 * Signature: (JLorg/opensearch/knn/index/store/IndexOutputWithBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_writeIndex
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    loadIndexWithStream
 * Signature: (Lorg/opensearch/knn/index/store/IndexInputWithBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_loadIndexWithStream
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    queryIndex
 * Signature: (J[FILjava/util/Map;)[Lorg/opensearch/knn/index/query/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_queryIndex
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jobject);

/*
 * Class:     org_opensearch_knn_sandbox_bruteforce_BruteForceService
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_sandbox_bruteforce_BruteForceService_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
